### ISSUE TITLE
Initialization takes too much time

### ISSUE THREAD

**Issue by ghost** [mobindustry/emojikeyboard#1]
When i initialise this keyboard my activity takes too much time to load. Any solution please.

I tried using async task but i failed due to touching UI in wronf thread exception.

**Comment by frontiertsymbal** [comment]
Initialize keyboard on start application in background thread. After that you can open keyboard faster. You can research https://github.com/rovkinmax/tchalange project - initialization is running with using RxAndroid

**Comment by ghost** [comment]
Yes but first time it takes too much time.

Do you know how can i initialize it in background thread?

**Comment by frontiertsymbal** [comment]
Probably create service and run this operation in it. https://github.com/mobindustry/mobigram/blob/master/app/src/main/java/net/mobindustry/mobigram/core/service/CreateGalleryThumbs.java for example.

**Comment by ghost** [comment]
Thanks for putting link.

Will look at it and let you know.

**Comment by ghost** [comment]
Facing this exception

 FATAL EXCEPTION: pool-4-thread-1
                                                             android.view.InflateException: Binary XML file line #21: Error inflating class EditText
                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                                 at android.view.View.inflate(View.java:16490)
                                                                 at net.mobindustry.emojilib.EmojiPanel.<init>(EmojiPanel.java:47)

Actually i have to use view, let me past my code so that things are very clear.

 mPanel = new EmojiPanel(this, mFrameLayout, new EmojiPanel.EmojiClickCallback() {
            @Override
            public void sendClicked(Spannable span) {

```
            String messageText = span.toString();
            if (TextUtils.isEmpty(messageText)) {
                return;
            }
            ChatMessage chatMessage = new ChatMessage();
            chatMessage.setMessage(messageText);
            chatMessage.setDate(DateUtils.getCurrentDateTime());
            chatMessage.setMe(true);
            chatMessage.setUnread(true);
            chatMessage.setChatStreamId(ChatActivity.this.mChatStreamId);

            ChatActivity.this.sendChatMessage(ChatActivity.this.mBuddyId,chatMessage);


            displayMessage(chatMessage);
        }

        @Override
        public void stickerClicked(String path) {
            //mSticker.setImageURI(Uri.parse(path));
        }
    });

    //Set default icons for buttons
    //panel.iconsInit();

    //or if you need custom icons for buttons
    mPanel.iconsInit(R.mipmap.ic_msg_panel_smiles, R.mipmap.ic_chat_send);

    //initialise panel
    mPanel.init();

    mParser = mPanel.getParser();
```

**Comment by ghost** [comment]
Inside Emoji.java  this function cause delay.

public void makeEmoji(EmojiCallback callback) {

complete code is 

```
public void makeEmoji(EmojiCallback callback) {
        loadEmojiAsync(0);
        loadEmojiAsync(1);
        loadEmojiAsync(2);
        loadEmojiAsync(3);
        boolean loaded = loadEmoji(4);
        while (loaded) {
            callback.loaded();
            break;
        }
    }
```

Though you have write it async why it is not doing it's work asynchronously?

**Comment by tonilopezmr** [comment]
@ahesanali do you resolved?

**Comment by tonilopezmr** [comment]
I have solved in `makeEmoji`, i have commented all loadEmojiAsync because doesn't do nothing, and make `loadEmoji(4)` async with a handler to back to ui when it ends and call `callback.loaded()`

**Comment by ghost** [comment]
In makeEmoji what  i have changed and got little bit improvement.

```
     callback.loaded();
        loadEmojiAsync(0);
        loadEmojiAsync(1);
        loadEmojiAsync(2);
        loadEmojiAsync(3);
        loadEmojiAsync(4);
//        boolean loaded = loadEmoji(4);
//        while (loaded) {
//            callback.loaded();
//            break;
//        }

But what are you saying i can't understand. Can you please add code to support your comment.
```

**Comment by ghost** [comment]
@tonilopezmr have you understood about what i have posted?
I can't understand what you are saying. is it possible for you to post some code?

**Comment by tonilopezmr** [comment]
@ahesanali have a look this [PR](https://github.com/mobindustry/emojikeyboard/pull/2/commits/481011aed94f902c95896e7fc4c94ce367719ecd)

**Comment by ghost** [comment]
@toni your trick works. Got some performance improvement.
